### ISSUE TITLE
Convert Binary Search Tree to Min Head

### ISSUE THREAD

**Issue by vaibhavpathak999** [vaibhavpathak999/Algorithms#28]

**Comment by Aaryan8751** [comment]
@vaibhavpathak999 please assign this issue to me And I think heap will come instead of head

**Comment by mendoza** [comment]
Hi, I would to help you out on this issue, assign me when you can!

**Comment by mendoza** [comment]
@vaibhavpathak999 someone else made the PR I checked it, and it looks great, so I won't make a new one, but thanks!
