### ISSUE TITLE
Reverse a path in BST using Min Head

### ISSUE THREAD

**Issue by vaibhavpathak999** [vaibhavpathak999/Algorithms#30]

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue

**Comment by navjotdadwal** [comment]
should i write function or full input output also you want?

**Comment by vaibhavpathak999** [comment]
@navjotdadwal please do it by taking input and output
